// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Slutprojekt.Infrastructure.Persistance;

#nullable disable

namespace Slutprojekt.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20250609091546_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Slutprojekt.Domain.Entities.Breed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BreedName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BreedType")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Breeds");

                    b.HasData(
                        new
                        {
                            Id = 10,
                            BreedName = "Collie, långhårig",
                            BreedType = 1,
                            Description = "Massa mjuk päls, elegant, lättlärd och gillar aktiviteter"
                        },
                        new
                        {
                            Id = 9,
                            BreedName = "Vit herdehud",
                            BreedType = 1,
                            Description = "Livlig, lättlärd sällskapshund med behov av aktivitet"
                        },
                        new
                        {
                            Id = 8,
                            BreedName = "Tysk schäferhund",
                            BreedType = 1,
                            Description = "Samarbetsvillig, livlig och uppmärksam jobbkompis"
                        },
                        new
                        {
                            Id = 23,
                            BreedName = "Boxer",
                            BreedType = 2,
                            Description = "Alert, arbetsvillig och livsglad bästa vän"
                        },
                        new
                        {
                            Id = 24,
                            BreedName = "Grand danois",
                            BreedType = 2,
                            Description = "Trofast, stor, stark och pampig"
                        },
                        new
                        {
                            Id = 25,
                            BreedName = "Leonberger",
                            BreedType = 2,
                            Description = "Behaglig och följsam med behov av fast hand"
                        },
                        new
                        {
                            Id = 36,
                            BreedName = "Bedlingtonterrier",
                            BreedType = 3,
                            Description = "Annorlunda utseende, charmig med stark vilja."
                        },
                        new
                        {
                            Id = 47,
                            BreedName = "Tax",
                            BreedType = 4,
                            Description = "Vänlig, envis och uthållig trots sina korta ben"
                        },
                        new
                        {
                            Id = 5,
                            BreedName = "Tysk spets/mittelspitz",
                            BreedType = 5,
                            Description = "Livlig, lättlärd pälsboll som hänger med"
                        },
                        new
                        {
                            Id = 66,
                            BreedName = "Basset hound",
                            BreedType = 6,
                            Description = "Social, tillgiven kortbent spårexpert"
                        },
                        new
                        {
                            Id = 67,
                            BreedName = "Beagle",
                            BreedType = 6,
                            Description = "Envis, arbetsvillig och glad"
                        },
                        new
                        {
                            Id = 71,
                            BreedName = "Engelsk setter",
                            BreedType = 7,
                            Description = "Energisk och krävande med passion för fågeljakt"
                        },
                        new
                        {
                            Id = 33,
                            BreedName = "Golden retriever",
                            BreedType = 8,
                            Description = "Vänlig och aktiv med stor passion för vatten"
                        },
                        new
                        {
                            Id = 32,
                            BreedName = "Labrador retriever",
                            BreedType = 8,
                            Description = "Social och stark apportör som är duktig på det mesta"
                        },
                        new
                        {
                            Id = 11,
                            BreedName = "Chihuahua, korthårig",
                            BreedType = 9,
                            Description = "Liten och sällskaplig hund som kan ta ton (vill inte bli uppäten!)"
                        },
                        new
                        {
                            Id = 14,
                            BreedName = "Afghanhund",
                            BreedType = 10,
                            Description = "Självständig skönhet med böljande päls."
                        },
                        new
                        {
                            Id = 12,
                            BreedName = "Greyhound",
                            BreedType = 10,
                            Description = "Vänlig, envis, stor och specialist på kapplöpning."
                        });
                });

            modelBuilder.Entity("Slutprojekt.Domain.Entities.BreedType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BreedTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BreedTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BreedTypeName = "Grupp 1 - Vall-, boskaps- och herdehundar"
                        },
                        new
                        {
                            Id = 2,
                            BreedTypeName = "Grupp 2 - Schnauzer och pinscher, molosser och bergshundar samt sennenhundar"
                        },
                        new
                        {
                            Id = 3,
                            BreedTypeName = "Grupp 3 - Terrier"
                        },
                        new
                        {
                            Id = 4,
                            BreedTypeName = "Grupp 4 - Taxar"
                        },
                        new
                        {
                            Id = 5,
                            BreedTypeName = "Grupp 5 - Spetsar och raser av urhundstyp"
                        },
                        new
                        {
                            Id = 6,
                            BreedTypeName = "Grupp 6 - Drivande hundar samt sök- och spårhundar"
                        },
                        new
                        {
                            Id = 7,
                            BreedTypeName = "Grupp 7 - Stående fågelhundar"
                        },
                        new
                        {
                            Id = 8,
                            BreedTypeName = "Grupp 8 - Stötande hundar, apporterande hundar och vattenhundar"
                        },
                        new
                        {
                            Id = 9,
                            BreedTypeName = "Grupp 9 - Sällskapshundar"
                        },
                        new
                        {
                            Id = 10,
                            BreedTypeName = "Grupp 10 - Vinthundar"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
